// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lity_fim_cpp
Rcpp::List lity_fim_cpp(const Rcpp::NumericMatrix& Dmu_input, const Rcpp::NumericMatrix& V_input, const Rcpp::List& dV, double tolerance);
RcppExport SEXP _LibeRality_lity_fim_cpp(SEXP Dmu_inputSEXP, SEXP V_inputSEXP, SEXP dVSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Dmu_input(Dmu_inputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type V_input(V_inputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dV(dVSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(lity_fim_cpp(Dmu_input, V_input, dV, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// lity_matrix_metrics_cpp
Rcpp::List lity_matrix_metrics_cpp(const Rcpp::NumericMatrix& information_input, double tolerance);
RcppExport SEXP _LibeRality_lity_matrix_metrics_cpp(SEXP information_inputSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type information_input(information_inputSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(lity_matrix_metrics_cpp(information_input, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRality_lity_fim_cpp", (DL_FUNC) &_LibeRality_lity_fim_cpp, 4},
    {"_LibeRality_lity_matrix_metrics_cpp", (DL_FUNC) &_LibeRality_lity_matrix_metrics_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LibeRality(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
