# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lity_fim_cpp <- function(Dmu, V, dV, tolerance = 1e-10) {
    .Call(`_LibeRality_lity_fim_cpp`, Dmu, V, dV, tolerance)
}

lity_matrix_metrics_cpp <- function(information, tolerance = 1e-10) {
    .Call(`_LibeRality_lity_matrix_metrics_cpp`, information, tolerance)
}

